"""Add manual entry columns to UserScans

Revision ID: 14f0558d8ec5
Revises: 
Create Date: 2025-01-19 16:57:23.817493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14f0558d8ec5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('food_log')
    with op.batch_alter_table('user_scans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('manual_name', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('manual_ingredients', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('manual_nutritional_values', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('picture_path', sa.String(length=200), nullable=True))
        batch_op.alter_column('scanned_data_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('manual_data')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_scans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('manual_data', sa.TEXT(), nullable=True))
        batch_op.alter_column('scanned_data_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('picture_path')
        batch_op.drop_column('manual_nutritional_values')
        batch_op.drop_column('manual_ingredients')
        batch_op.drop_column('manual_name')

    op.create_table('food_log',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('barcode', sa.VARCHAR(length=50), nullable=False),
    sa.Column('product_name', sa.VARCHAR(length=200), nullable=True),
    sa.Column('ingredients', sa.TEXT(), nullable=True),
    sa.Column('nutritional_values', sa.TEXT(), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
